// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pos_dict.proto
// Protobuf C++ Version: 5.29.5

#ifndef pos_5fdict_2eproto_2epb_2eh
#define pos_5fdict_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_pos_5fdict_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_pos_5fdict_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_pos_5fdict_2eproto;
namespace htpostagger {
class PosDict;
struct PosDictDefaultTypeInternal;
extern PosDictDefaultTypeInternal _PosDict_default_instance_;
class PosDict_I2pEntry_DoNotUse;
struct PosDict_I2pEntry_DoNotUseDefaultTypeInternal;
extern PosDict_I2pEntry_DoNotUseDefaultTypeInternal _PosDict_I2pEntry_DoNotUse_default_instance_;
class PosDict_P2iEntry_DoNotUse;
struct PosDict_P2iEntry_DoNotUseDefaultTypeInternal;
extern PosDict_P2iEntry_DoNotUseDefaultTypeInternal _PosDict_P2iEntry_DoNotUse_default_instance_;
}  // namespace htpostagger
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace htpostagger {

// ===================================================================


// -------------------------------------------------------------------

class PosDict_P2iEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, ::int64_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT64> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, ::int64_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64>;
  PosDict_P2iEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PosDict_P2iEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit PosDict_P2iEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const PosDict_P2iEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const PosDict_P2iEntry_DoNotUse*>(
        &_PosDict_P2iEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_pos_5fdict_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      40, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class PosDict_I2pEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          ::int64_t, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      ::int64_t, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  PosDict_I2pEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PosDict_I2pEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit PosDict_I2pEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const PosDict_I2pEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const PosDict_I2pEntry_DoNotUse*>(
        &_PosDict_I2pEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_pos_5fdict_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      42, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class PosDict final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:htpostagger.PosDict) */ {
 public:
  inline PosDict() : PosDict(nullptr) {}
  ~PosDict() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PosDict* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PosDict));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PosDict(
      ::google::protobuf::internal::ConstantInitialized);

  inline PosDict(const PosDict& from) : PosDict(nullptr, from) {}
  inline PosDict(PosDict&& from) noexcept
      : PosDict(nullptr, std::move(from)) {}
  inline PosDict& operator=(const PosDict& from) {
    CopyFrom(from);
    return *this;
  }
  inline PosDict& operator=(PosDict&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PosDict& default_instance() {
    return *internal_default_instance();
  }
  static inline const PosDict* internal_default_instance() {
    return reinterpret_cast<const PosDict*>(
        &_PosDict_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PosDict& a, PosDict& b) { a.Swap(&b); }
  inline void Swap(PosDict* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PosDict* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PosDict* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PosDict>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PosDict& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PosDict& from) { PosDict::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PosDict* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "htpostagger.PosDict"; }

 protected:
  explicit PosDict(::google::protobuf::Arena* arena);
  PosDict(::google::protobuf::Arena* arena, const PosDict& from);
  PosDict(::google::protobuf::Arena* arena, PosDict&& from) noexcept
      : PosDict(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kP2IFieldNumber = 1,
    kI2PFieldNumber = 2,
  };
  // map<string, int64> p2i = 1;
  int p2i_size() const;
  private:
  int _internal_p2i_size() const;

  public:
  void clear_p2i() ;
  const ::google::protobuf::Map<std::string, ::int64_t>& p2i() const;
  ::google::protobuf::Map<std::string, ::int64_t>* mutable_p2i();

  private:
  const ::google::protobuf::Map<std::string, ::int64_t>& _internal_p2i() const;
  ::google::protobuf::Map<std::string, ::int64_t>* _internal_mutable_p2i();

  public:
  // map<int64, string> i2p = 2;
  int i2p_size() const;
  private:
  int _internal_i2p_size() const;

  public:
  void clear_i2p() ;
  const ::google::protobuf::Map<::int64_t, std::string>& i2p() const;
  ::google::protobuf::Map<::int64_t, std::string>* mutable_i2p();

  private:
  const ::google::protobuf::Map<::int64_t, std::string>& _internal_i2p() const;
  ::google::protobuf::Map<::int64_t, std::string>* _internal_mutable_i2p();

  public:
  // @@protoc_insertion_point(class_scope:htpostagger.PosDict)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 2,
      34, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PosDict& from_msg);
    ::google::protobuf::internal::MapField<PosDict_P2iEntry_DoNotUse, std::string, ::int64_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT64>
        p2i_;
    ::google::protobuf::internal::MapField<PosDict_I2pEntry_DoNotUse, ::int64_t, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        i2p_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pos_5fdict_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PosDict

// map<string, int64> p2i = 1;
inline int PosDict::_internal_p2i_size() const {
  return _internal_p2i().size();
}
inline int PosDict::p2i_size() const {
  return _internal_p2i_size();
}
inline void PosDict::clear_p2i() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p2i_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int64_t>& PosDict::_internal_p2i() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.p2i_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int64_t>& PosDict::p2i() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:htpostagger.PosDict.p2i)
  return _internal_p2i();
}
inline ::google::protobuf::Map<std::string, ::int64_t>* PosDict::_internal_mutable_p2i() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.p2i_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int64_t>* PosDict::mutable_p2i() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:htpostagger.PosDict.p2i)
  return _internal_mutable_p2i();
}

// map<int64, string> i2p = 2;
inline int PosDict::_internal_i2p_size() const {
  return _internal_i2p().size();
}
inline int PosDict::i2p_size() const {
  return _internal_i2p_size();
}
inline void PosDict::clear_i2p() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i2p_.Clear();
}
inline const ::google::protobuf::Map<::int64_t, std::string>& PosDict::_internal_i2p() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i2p_.GetMap();
}
inline const ::google::protobuf::Map<::int64_t, std::string>& PosDict::i2p() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:htpostagger.PosDict.i2p)
  return _internal_i2p();
}
inline ::google::protobuf::Map<::int64_t, std::string>* PosDict::_internal_mutable_i2p() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.i2p_.MutableMap();
}
inline ::google::protobuf::Map<::int64_t, std::string>* PosDict::mutable_i2p() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:htpostagger.PosDict.i2p)
  return _internal_mutable_i2p();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace htpostagger


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // pos_5fdict_2eproto_2epb_2eh
