// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pos_dict.proto
// Protobuf C++ Version: 5.29.5

#include "pos_dict.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace htpostagger {
              template <typename>
PROTOBUF_CONSTEXPR PosDict_P2iEntry_DoNotUse::PosDict_P2iEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : PosDict_P2iEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : PosDict_P2iEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct PosDict_P2iEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PosDict_P2iEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PosDict_P2iEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PosDict_P2iEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PosDict_P2iEntry_DoNotUseDefaultTypeInternal _PosDict_P2iEntry_DoNotUse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR PosDict_I2pEntry_DoNotUse::PosDict_I2pEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : PosDict_I2pEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : PosDict_I2pEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct PosDict_I2pEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PosDict_I2pEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PosDict_I2pEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PosDict_I2pEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PosDict_I2pEntry_DoNotUseDefaultTypeInternal _PosDict_I2pEntry_DoNotUse_default_instance_;

inline constexpr PosDict::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : p2i_{},
        i2p_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PosDict::PosDict(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PosDictDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PosDictDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PosDictDefaultTypeInternal() {}
  union {
    PosDict _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PosDictDefaultTypeInternal _PosDict_default_instance_;
}  // namespace htpostagger
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_pos_5fdict_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_pos_5fdict_2eproto = nullptr;
const ::uint32_t
    TableStruct_pos_5fdict_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_P2iEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_P2iEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_P2iEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_P2iEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_I2pEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_I2pEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_I2pEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict_I2pEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict, _impl_.p2i_),
        PROTOBUF_FIELD_OFFSET(::htpostagger::PosDict, _impl_.i2p_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::htpostagger::PosDict_P2iEntry_DoNotUse)},
        {12, 22, -1, sizeof(::htpostagger::PosDict_I2pEntry_DoNotUse)},
        {24, -1, -1, sizeof(::htpostagger::PosDict)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::htpostagger::_PosDict_P2iEntry_DoNotUse_default_instance_._instance,
    &::htpostagger::_PosDict_I2pEntry_DoNotUse_default_instance_._instance,
    &::htpostagger::_PosDict_default_instance_._instance,
};
const char descriptor_table_protodef_pos_5fdict_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016pos_dict.proto\022\013htpostagger\"\271\001\n\007PosDic"
    "t\022*\n\003p2i\030\001 \003(\0132\035.htpostagger.PosDict.P2i"
    "Entry\022*\n\003i2p\030\002 \003(\0132\035.htpostagger.PosDict"
    ".I2pEntry\032*\n\010P2iEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va"
    "lue\030\002 \001(\003:\0028\001\032*\n\010I2pEntry\022\013\n\003key\030\001 \001(\003\022\r"
    "\n\005value\030\002 \001(\t:\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_pos_5fdict_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_pos_5fdict_2eproto = {
    false,
    false,
    225,
    descriptor_table_protodef_pos_5fdict_2eproto,
    "pos_dict.proto",
    &descriptor_table_pos_5fdict_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_pos_5fdict_2eproto::offsets,
    file_level_enum_descriptors_pos_5fdict_2eproto,
    file_level_service_descriptors_pos_5fdict_2eproto,
};
namespace htpostagger {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              PosDict_P2iEntry_DoNotUse::PosDict_P2iEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              PosDict_P2iEntry_DoNotUse::PosDict_P2iEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              PosDict_P2iEntry_DoNotUse::PosDict_P2iEntry_DoNotUse() : SuperType() {}
              PosDict_P2iEntry_DoNotUse::PosDict_P2iEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* PosDict_P2iEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) PosDict_P2iEntry_DoNotUse(arena);
              }
              constexpr auto PosDict_P2iEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PosDict_P2iEntry_DoNotUse),
                                                          alignof(PosDict_P2iEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull PosDict_P2iEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_PosDict_P2iEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &PosDict_P2iEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<PosDict_P2iEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &PosDict_P2iEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &PosDict_P2iEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(PosDict_P2iEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &PosDict_P2iEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_pos_5fdict_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* PosDict_P2iEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> PosDict_P2iEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PosDict_P2iEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::htpostagger::PosDict_P2iEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PosDict_P2iEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PosDict_P2iEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PosDict_P2iEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(PosDict_P2iEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 value = 2;
    {PROTOBUF_FIELD_OFFSET(PosDict_P2iEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\34\3\0\0\0\0\0\0"
    "htpostagger.PosDict.P2iEntry"
    "key"
  }},
};

// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              PosDict_I2pEntry_DoNotUse::PosDict_I2pEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              PosDict_I2pEntry_DoNotUse::PosDict_I2pEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              PosDict_I2pEntry_DoNotUse::PosDict_I2pEntry_DoNotUse() : SuperType() {}
              PosDict_I2pEntry_DoNotUse::PosDict_I2pEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* PosDict_I2pEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) PosDict_I2pEntry_DoNotUse(arena);
              }
              constexpr auto PosDict_I2pEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PosDict_I2pEntry_DoNotUse),
                                                          alignof(PosDict_I2pEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull PosDict_I2pEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_PosDict_I2pEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &PosDict_I2pEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<PosDict_I2pEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &PosDict_I2pEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &PosDict_I2pEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(PosDict_I2pEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &PosDict_I2pEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_pos_5fdict_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* PosDict_I2pEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> PosDict_I2pEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PosDict_I2pEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::htpostagger::PosDict_I2pEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PosDict_I2pEntry_DoNotUse, _impl_.value_)}},
    // int64 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PosDict_I2pEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PosDict_I2pEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 key = 1;
    {PROTOBUF_FIELD_OFFSET(PosDict_I2pEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(PosDict_I2pEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\5\0\0\0\0\0"
    "htpostagger.PosDict.I2pEntry"
    "value"
  }},
};

// ===================================================================

class PosDict::_Internal {
 public:
};

PosDict::PosDict(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:htpostagger.PosDict)
}
inline PROTOBUF_NDEBUG_INLINE PosDict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::htpostagger::PosDict& from_msg)
      : p2i_{visibility, arena, from.p2i_},
        i2p_{visibility, arena, from.i2p_},
        _cached_size_{0} {}

PosDict::PosDict(
    ::google::protobuf::Arena* arena,
    const PosDict& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PosDict* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:htpostagger.PosDict)
}
inline PROTOBUF_NDEBUG_INLINE PosDict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : p2i_{visibility, arena},
        i2p_{visibility, arena},
        _cached_size_{0} {}

inline void PosDict::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PosDict::~PosDict() {
  // @@protoc_insertion_point(destructor:htpostagger.PosDict)
  SharedDtor(*this);
}
inline void PosDict::SharedDtor(MessageLite& self) {
  PosDict& this_ = static_cast<PosDict&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PosDict::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PosDict(arena);
}
constexpr auto PosDict::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PosDict, _impl_.p2i_) +
          decltype(PosDict::_impl_.p2i_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PosDict, _impl_.p2i_) +
          decltype(PosDict::_impl_.p2i_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PosDict, _impl_.i2p_) +
          decltype(PosDict::_impl_.i2p_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PosDict, _impl_.i2p_) +
          decltype(PosDict::_impl_.i2p_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(PosDict), alignof(PosDict), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PosDict::PlacementNew_,
                                 sizeof(PosDict),
                                 alignof(PosDict));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PosDict::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PosDict_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PosDict::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PosDict>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PosDict::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PosDict>(), &PosDict::ByteSizeLong,
            &PosDict::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PosDict, _impl_._cached_size_),
        false,
    },
    &PosDict::kDescriptorMethods,
    &descriptor_table_pos_5fdict_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PosDict::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 34, 2> PosDict::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::htpostagger::PosDict>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, int64> p2i = 1;
    {PROTOBUF_FIELD_OFFSET(PosDict, _impl_.p2i_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<int64, string> i2p = 2;
    {PROTOBUF_FIELD_OFFSET(PosDict, _impl_.i2p_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(PosDict()._impl_.p2i_)>(
        1, 0, 0, 9,
        3)},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(PosDict()._impl_.i2p_)>(
        1, 0, 0, 3,
        9)},
  }}, {{
    "\23\3\3\0\0\0\0\0"
    "htpostagger.PosDict"
    "p2i"
    "i2p"
  }},
};

PROTOBUF_NOINLINE void PosDict::Clear() {
// @@protoc_insertion_point(message_clear_start:htpostagger.PosDict)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.p2i_.Clear();
  _impl_.i2p_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PosDict::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PosDict& this_ = static_cast<const PosDict&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PosDict::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PosDict& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:htpostagger.PosDict)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // map<string, int64> p2i = 1;
          if (!this_._internal_p2i().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int64_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int64_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT64>;
            const auto& field = this_._internal_p2i();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "htpostagger.PosDict.p2i");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "htpostagger.PosDict.p2i");
              }
            }
          }

          // map<int64, string> i2p = 2;
          if (!this_._internal_i2p().empty()) {
            using MapType = ::google::protobuf::Map<::int64_t, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<::int64_t, std::string,
                                           _pbi::WireFormatLite::TYPE_INT64,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_i2p();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "htpostagger.PosDict.i2p");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "htpostagger.PosDict.i2p");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:htpostagger.PosDict)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PosDict::ByteSizeLong(const MessageLite& base) {
          const PosDict& this_ = static_cast<const PosDict&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PosDict::ByteSizeLong() const {
          const PosDict& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:htpostagger.PosDict)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, int64> p2i = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_p2i_size());
              for (const auto& entry : this_._internal_p2i()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int64_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT64>::ByteSizeLong(entry.first, entry.second);
              }
            }
            // map<int64, string> i2p = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_i2p_size());
              for (const auto& entry : this_._internal_i2p()) {
                total_size += _pbi::MapEntryFuncs<::int64_t, std::string,
                                               _pbi::WireFormatLite::TYPE_INT64,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PosDict::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PosDict*>(&to_msg);
  auto& from = static_cast<const PosDict&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:htpostagger.PosDict)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.p2i_.MergeFrom(from._impl_.p2i_);
  _this->_impl_.i2p_.MergeFrom(from._impl_.i2p_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PosDict::CopyFrom(const PosDict& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:htpostagger.PosDict)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PosDict::InternalSwap(PosDict* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.p2i_.InternalSwap(&other->_impl_.p2i_);
  _impl_.i2p_.InternalSwap(&other->_impl_.i2p_);
}

::google::protobuf::Metadata PosDict::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace htpostagger
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_pos_5fdict_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
