// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tok_dict.proto
// Protobuf C++ Version: 5.29.5

#ifndef tok_5fdict_2eproto_2epb_2eh
#define tok_5fdict_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_tok_5fdict_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_tok_5fdict_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_tok_5fdict_2eproto;
namespace httokenizer {
class TokDict;
struct TokDictDefaultTypeInternal;
extern TokDictDefaultTypeInternal _TokDict_default_instance_;
class TokDict_DictEntry_DoNotUse;
struct TokDict_DictEntry_DoNotUseDefaultTypeInternal;
extern TokDict_DictEntry_DoNotUseDefaultTypeInternal _TokDict_DictEntry_DoNotUse_default_instance_;
}  // namespace httokenizer
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace httokenizer {

// ===================================================================


// -------------------------------------------------------------------

class TokDict_DictEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, ::int64_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT64> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, ::int64_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64>;
  TokDict_DictEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TokDict_DictEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit TokDict_DictEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const TokDict_DictEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const TokDict_DictEntry_DoNotUse*>(
        &_TokDict_DictEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_tok_5fdict_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      41, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class TokDict final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:httokenizer.TokDict) */ {
 public:
  inline TokDict() : TokDict(nullptr) {}
  ~TokDict() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TokDict* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TokDict));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TokDict(
      ::google::protobuf::internal::ConstantInitialized);

  inline TokDict(const TokDict& from) : TokDict(nullptr, from) {}
  inline TokDict(TokDict&& from) noexcept
      : TokDict(nullptr, std::move(from)) {}
  inline TokDict& operator=(const TokDict& from) {
    CopyFrom(from);
    return *this;
  }
  inline TokDict& operator=(TokDict&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TokDict& default_instance() {
    return *internal_default_instance();
  }
  static inline const TokDict* internal_default_instance() {
    return reinterpret_cast<const TokDict*>(
        &_TokDict_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TokDict& a, TokDict& b) { a.Swap(&b); }
  inline void Swap(TokDict* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TokDict* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TokDict* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TokDict>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TokDict& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TokDict& from) { TokDict::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TokDict* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "httokenizer.TokDict"; }

 protected:
  explicit TokDict(::google::protobuf::Arena* arena);
  TokDict(::google::protobuf::Arena* arena, const TokDict& from);
  TokDict(::google::protobuf::Arena* arena, TokDict&& from) noexcept
      : TokDict(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDictFieldNumber = 1,
  };
  // map<string, int64> dict = 1;
  int dict_size() const;
  private:
  int _internal_dict_size() const;

  public:
  void clear_dict() ;
  const ::google::protobuf::Map<std::string, ::int64_t>& dict() const;
  ::google::protobuf::Map<std::string, ::int64_t>* mutable_dict();

  private:
  const ::google::protobuf::Map<std::string, ::int64_t>& _internal_dict() const;
  ::google::protobuf::Map<std::string, ::int64_t>* _internal_mutable_dict();

  public:
  // @@protoc_insertion_point(class_scope:httokenizer.TokDict)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      32, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TokDict& from_msg);
    ::google::protobuf::internal::MapField<TokDict_DictEntry_DoNotUse, std::string, ::int64_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT64>
        dict_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tok_5fdict_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TokDict

// map<string, int64> dict = 1;
inline int TokDict::_internal_dict_size() const {
  return _internal_dict().size();
}
inline int TokDict::dict_size() const {
  return _internal_dict_size();
}
inline void TokDict::clear_dict() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dict_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int64_t>& TokDict::_internal_dict() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dict_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int64_t>& TokDict::dict() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:httokenizer.TokDict.dict)
  return _internal_dict();
}
inline ::google::protobuf::Map<std::string, ::int64_t>* TokDict::_internal_mutable_dict() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dict_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int64_t>* TokDict::mutable_dict() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:httokenizer.TokDict.dict)
  return _internal_mutable_dict();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace httokenizer


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // tok_5fdict_2eproto_2epb_2eh
