// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tok_dict.proto
// Protobuf C++ Version: 5.29.5

#include "tok_dict.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace httokenizer {
              template <typename>
PROTOBUF_CONSTEXPR TokDict_DictEntry_DoNotUse::TokDict_DictEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : TokDict_DictEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : TokDict_DictEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct TokDict_DictEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokDict_DictEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokDict_DictEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TokDict_DictEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokDict_DictEntry_DoNotUseDefaultTypeInternal _TokDict_DictEntry_DoNotUse_default_instance_;

inline constexpr TokDict::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dict_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TokDict::TokDict(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TokDictDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokDictDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokDictDefaultTypeInternal() {}
  union {
    TokDict _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokDictDefaultTypeInternal _TokDict_default_instance_;
}  // namespace httokenizer
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_tok_5fdict_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tok_5fdict_2eproto = nullptr;
const ::uint32_t
    TableStruct_tok_5fdict_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::httokenizer::TokDict_DictEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::httokenizer::TokDict_DictEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::httokenizer::TokDict_DictEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::httokenizer::TokDict_DictEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::httokenizer::TokDict, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::httokenizer::TokDict, _impl_.dict_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::httokenizer::TokDict_DictEntry_DoNotUse)},
        {12, -1, -1, sizeof(::httokenizer::TokDict)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::httokenizer::_TokDict_DictEntry_DoNotUse_default_instance_._instance,
    &::httokenizer::_TokDict_default_instance_._instance,
};
const char descriptor_table_protodef_tok_5fdict_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016tok_dict.proto\022\013httokenizer\"d\n\007TokDict"
    "\022,\n\004dict\030\001 \003(\0132\036.httokenizer.TokDict.Dic"
    "tEntry\032+\n\tDictEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu"
    "e\030\002 \001(\003:\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_tok_5fdict_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_tok_5fdict_2eproto = {
    false,
    false,
    139,
    descriptor_table_protodef_tok_5fdict_2eproto,
    "tok_dict.proto",
    &descriptor_table_tok_5fdict_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_tok_5fdict_2eproto::offsets,
    file_level_enum_descriptors_tok_5fdict_2eproto,
    file_level_service_descriptors_tok_5fdict_2eproto,
};
namespace httokenizer {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              TokDict_DictEntry_DoNotUse::TokDict_DictEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              TokDict_DictEntry_DoNotUse::TokDict_DictEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              TokDict_DictEntry_DoNotUse::TokDict_DictEntry_DoNotUse() : SuperType() {}
              TokDict_DictEntry_DoNotUse::TokDict_DictEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* TokDict_DictEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) TokDict_DictEntry_DoNotUse(arena);
              }
              constexpr auto TokDict_DictEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TokDict_DictEntry_DoNotUse),
                                                          alignof(TokDict_DictEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull TokDict_DictEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_TokDict_DictEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &TokDict_DictEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<TokDict_DictEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &TokDict_DictEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &TokDict_DictEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(TokDict_DictEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &TokDict_DictEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_tok_5fdict_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* TokDict_DictEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> TokDict_DictEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TokDict_DictEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::httokenizer::TokDict_DictEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TokDict_DictEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TokDict_DictEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TokDict_DictEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(TokDict_DictEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 value = 2;
    {PROTOBUF_FIELD_OFFSET(TokDict_DictEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\35\3\0\0\0\0\0\0"
    "httokenizer.TokDict.DictEntry"
    "key"
  }},
};

// ===================================================================

class TokDict::_Internal {
 public:
};

TokDict::TokDict(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:httokenizer.TokDict)
}
inline PROTOBUF_NDEBUG_INLINE TokDict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::httokenizer::TokDict& from_msg)
      : dict_{visibility, arena, from.dict_},
        _cached_size_{0} {}

TokDict::TokDict(
    ::google::protobuf::Arena* arena,
    const TokDict& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TokDict* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:httokenizer.TokDict)
}
inline PROTOBUF_NDEBUG_INLINE TokDict::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : dict_{visibility, arena},
        _cached_size_{0} {}

inline void TokDict::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TokDict::~TokDict() {
  // @@protoc_insertion_point(destructor:httokenizer.TokDict)
  SharedDtor(*this);
}
inline void TokDict::SharedDtor(MessageLite& self) {
  TokDict& this_ = static_cast<TokDict&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TokDict::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TokDict(arena);
}
constexpr auto TokDict::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TokDict, _impl_.dict_) +
          decltype(TokDict::_impl_.dict_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TokDict, _impl_.dict_) +
          decltype(TokDict::_impl_.dict_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TokDict), alignof(TokDict), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TokDict::PlacementNew_,
                                 sizeof(TokDict),
                                 alignof(TokDict));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TokDict::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TokDict_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TokDict::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TokDict>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TokDict::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TokDict>(), &TokDict::ByteSizeLong,
            &TokDict::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TokDict, _impl_._cached_size_),
        false,
    },
    &TokDict::kDescriptorMethods,
    &descriptor_table_tok_5fdict_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TokDict::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 32, 2> TokDict::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::httokenizer::TokDict>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, int64> dict = 1;
    {PROTOBUF_FIELD_OFFSET(TokDict, _impl_.dict_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(TokDict()._impl_.dict_)>(
        1, 0, 0, 9,
        3)},
  }}, {{
    "\23\4\0\0\0\0\0\0"
    "httokenizer.TokDict"
    "dict"
  }},
};

PROTOBUF_NOINLINE void TokDict::Clear() {
// @@protoc_insertion_point(message_clear_start:httokenizer.TokDict)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dict_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TokDict::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TokDict& this_ = static_cast<const TokDict&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TokDict::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TokDict& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:httokenizer.TokDict)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // map<string, int64> dict = 1;
          if (!this_._internal_dict().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int64_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int64_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT64>;
            const auto& field = this_._internal_dict();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "httokenizer.TokDict.dict");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    1, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "httokenizer.TokDict.dict");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:httokenizer.TokDict)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TokDict::ByteSizeLong(const MessageLite& base) {
          const TokDict& this_ = static_cast<const TokDict&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TokDict::ByteSizeLong() const {
          const TokDict& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:httokenizer.TokDict)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, int64> dict = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_dict_size());
              for (const auto& entry : this_._internal_dict()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int64_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT64>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TokDict::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TokDict*>(&to_msg);
  auto& from = static_cast<const TokDict&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:httokenizer.TokDict)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.dict_.MergeFrom(from._impl_.dict_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TokDict::CopyFrom(const TokDict& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:httokenizer.TokDict)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TokDict::InternalSwap(TokDict* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dict_.InternalSwap(&other->_impl_.dict_);
}

::google::protobuf::Metadata TokDict::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace httokenizer
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_tok_5fdict_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
